Initial Rust Backend
TaylorKNoah/FullStack-GroupProject-Spring22 pull request #2
Opened 2022-05-11 19:39 UTC by kesquerra

Backend API skeleton
- Logging
- Basic API routes
- Test users

2022-05-12 20:27 UTC, TaylorKNoah commented on backend/README.md
> +# Build Backend:
Can you add a section describing how to run the backend? ie what commands  to run.

2022-05-12 20:31 UTC, TaylorKNoah requested changes
Can you add a section in the README describing how to run the backend? ie what commands to run.

2022-05-12 20:38 UTC, kesquerra commented
The instructions to run the backend are in the README. As of right now, it just takes "cargo run" with rust installed.

2022-05-12 20:40 UTC, kesquerra commented
I did update the configuration to use a .env file recently. I'll update the README to reflect that, good catch!

2022-05-12 20:48 UTC, kesquerra commented
.env instructions added with link to example.env

2022-05-13 19:43 UTC, adam-taitano approved these changes
Compiled on my end, and seems to work, at least on the main '/ route.
I'll try to add some automated testing by the end of this weekend. Nice work.

2022-05-14 19:46 UTC, TaylorKNoah approved these changes
Looks good! Thanks!

2022-05-14 19:52 UTC, merged

2022-05-14 19:52 UTC, adam-taitano commented
Sweet solid stuff!